port: 8080
environment: DEVNET
triggerDCA:
  - vault: 3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV
    vaultProtoConfig: mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: 6PmcdLzbELLxaPc3Fq6FjiSj7wtjA4MEt1UCZBnHh6tw
    vaultTokenBAccount: 5q7HLgfvxmkqAK6QaEFYrNmvKvzQZjWJzjwRu4toi9Sw
    vaultTreasuryTokenBAccount: CrVdqMmYCbBs8zG2rmwdWgmsSArKTbMUv3qvTz8J6YWC
    tokenAMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenASymbol: SOL
    tokenBMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenBSymbol: USDC
    swapTokenMint: 5U7X6mgvmsu5sSUFWCXtPhsNMVmEyZ4zJzhgweVTjFfX
    swapTokenAAccount: 7cJ5h3JgGBYKt1QzD8z5veLvBQcaEuJMm9CyFp6c5XeG
    swapTokenBAccount: 6fg6TGxUjBKF5BBtreMVpDP7YGrnrizHsDaME1UE5ejy
    swapFeeAccount: Gj8DqPPVjgZwTjvvQA7gRzFE22fT3s9ztAYfiTim4HiH
    swapAuthority: 216G8d1QWwLmxw89Y5Kai69nE1MTzMPNMArX2mQ7KK2Z
    swap: 8Vx5D6dKfv1vyLzL6hdxB1KNnRr5yiHSaw8bDh5LVNAE
  - vault: 7rERMPGFMFi5k7jsQj3yXbW9uPDQj8FBx6vjwVXpknbh
    vaultProtoConfig: mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: 5y95dsjKJPaf94Kv8K6NbhyDYWswZycfcHNbwXMo6Xdk
    vaultTokenBAccount: 9B6zNC4ijKfgGjReicqzv5dEPhJMt2oDH97b4AjUAs9a
    vaultTreasuryTokenBAccount: ugY3pNYSKmMo4msf9VRVnf7SxFQXDqhNcjbNMKSW9gL
    tokenAMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenASymbol: USDC
    tokenBMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenBSymbol: SOL
    swapTokenMint: 8nkNWoyNA4NirnGdgdjXidLMKYAYQRXTkfE11cAbxtwm
    swapTokenAAccount: H5sC1foHR96vjWGRdTwsf9mRLMS6SYps8m94SXvRD184
    swapTokenBAccount: FNHjDkcWNCQVCgieTSj7tS5ZjD3ZhYhb3BUcQ2A4cNw7
    swapFeeAccount: 3iPD2fkDxkG6MT9vi58LZYFSKRZ5KW6inPDGaPbNMkAL
    swapAuthority: BFrB7mquMihDjCJxGPjduKizoyDixsrUWxy79w9LuNVf
    swap: 9ucf2YnXdimpPGBDwPqikNrNMnJMtaAzMYxrinWeersz
  - vault: 9qyL3EJncPi1ggLnZTJRRZ617PaXbSZ8YHYuycvwBFQF
    vaultProtoConfig: mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: CgsuFMFXuXa5NPufLxz6e2uD5M89ecQB9wvUnVkXqoQ9
    vaultTokenBAccount: 8YnN6gNe2FymR751kzd1D31Nd1qvuEt8xBdiombvAG2Z
    vaultTreasuryTokenBAccount: ugY3pNYSKmMo4msf9VRVnf7SxFQXDqhNcjbNMKSW9gL
    tokenAMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenASymbol: ETH
    tokenBMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenBSymbol: SOL
    swapTokenMint: 9qEaSrT6JUDPSP52chzCFiZYmSXLK5U3EJuc9nzgaeW3
    swapTokenAAccount: Ds6SFXDoHbZN1qfafguFAKUo6zJdt9JdaNptFBSCk9Dt
    swapTokenBAccount: Dv796LgvwgKhMDTuT6amsLQupCSQPPXrK2LcLXr8y5Te
    swapFeeAccount: BYb4FDLPEdGBi8kzAfD52p4jPtqkEibC9gmhs7LizN8y
    swapAuthority: DiKicQMELsLDoHHVttgqPeTndeABsdXsrD9jUsnjWWcs
    swap: 3f9XbWQZYiHY8QGUcG5ihmJ6jkCHvepweTj9WYcNKu9X
  - vault: 2gxv7Kcv595VxdJRCMSruvo3z7j5CJhBAnGXiNdGxfLE
    vaultProtoConfig: mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: 2joXoPdckR7yzJpf47KMBPvnUwHzj1VFv5ASWXhTezUz
    vaultTokenBAccount: 65uUqvqKzTTv47tCk46bnAVXWTPb72fooVyLXVxZd1uc
    vaultTreasuryTokenBAccount: 74eawbizDBEKKoY2EWhUFRnz9kH7U6hrjMe3xzYnEM5A
    tokenAMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenASymbol: USDC
    tokenBMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenBSymbol: ETH
    swapTokenMint: HrFiCMn4VWTLJgftdksjcP1Np7CCtKA512D9i6CeNPyD
    swapTokenAAccount: EaFUGLy1vGHy6djyMcLsgQq1ta8CCUw6D7ikuCfqqRxK
    swapTokenBAccount: Bd3ejFyWU83H2gHaPJrxP42MELYzm1kwmhb1sC1jckpU
    swapFeeAccount: Ewe9RGuNfa2sAd8v3hBjcaPVJ95EFkK1HTMEcSKCYSGN
    swapAuthority: EvfRrR8SSqRCdepYzuEHsX5SWbbF8uR943LtErcLfyf7
    swap: 6tF4EzuCAtCwCRuUroDmXHR7GqQXB8soejcZPHBp1wYz
  - vault: 2ryN4z5rCRexwKQrDtERgVA9b8W9GreYjT9v9q7q7zks
    vaultProtoConfig: mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: H4hArSuaAZtPB6UoGYQUp5LV6cLJHSw7a8XbU4Pra2Rm
    vaultTokenBAccount: D7pszKVvqEJ7geNDHMD5vWJtehraCKjwSjzo2gQwwPS5
    vaultTreasuryTokenBAccount: 74eawbizDBEKKoY2EWhUFRnz9kH7U6hrjMe3xzYnEM5A
    tokenAMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenASymbol: SOL
    tokenBMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenBSymbol: ETH
    swapTokenMint: 6yjg26o1QoaiN9ehP2TzTs5M1ndUKCh9j3WjHi8scnXR
    swapTokenAAccount: CHwDDRGyg88t29EsenrVziNULoGEdn9VVsRHaypsx99d
    swapTokenBAccount: Huwr1LCk1gyTHFic3BpiMdV9MXW26Cq42exZRsYHPvKY
    swapFeeAccount: 77F1sC93dy6ubdJmTSzjsTzRcD5Frk5Q6MsRU9jxk1o3
    swapAuthority: 88TUbCTWoyQo4YEfTzVRbjKpDrE4jYYP2LGvvSTA25X9
    swap: 8YhUpFGLG8hXwzHuaStNb39Vbjr6Nmj9JdRHExwJ7Jq9
  - vault: 9vLQxJTuycNBctAQvEmXUJpe3MEKgUugHxkiRjNMzczs
    vaultProtoConfig: CjxcyivgP69qEvXvKFbsYjTxavPWwh5UEWwtzbjodwer
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: GkAsh5LYfYzmat87kh9FKg2ss62vzSoRYJbbDD4DAjKk
    vaultTokenBAccount: 6QbfBoAGm2yTkg9WApj4sKexrucWDi1S5T3BS8YHuTuh
    vaultTreasuryTokenBAccount: E7oYHeM7v14tv7AjvsxD9tcXQMtLYvZRarTjQ1uqhjSW
    tokenAMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenASymbol: SOL
    tokenBMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenBSymbol: USDC
    swapTokenMint: 4EGRrgx3yshgBVH86YXXx7b5yWJvQcAxy7L5zHcgmzKp
    swapTokenAAccount: F66H9BgnJjj3T63BZYVgBL8YLz5K228JUti2YbtKAXcT
    swapTokenBAccount: rQZvZghpKGRPzaAfcieXQuJX2eTSDpj6vw6bZ7PcVbj
    swapFeeAccount: 4FuhmHURxUjDjQgvGaPSuZr8obdXoPHoLwepMpLwon7u
    swapAuthority: 3YX31J8UgmtMYGu5PfPNSjAbQQek6du9RbdTeoasqN4Q
    swap: Bp5932AZjC5yvFDKBwyUGhimAvesLs49Q6stQnWSMiMQ
  - vault: 827ynxorqgFQmUAhewqC5eNeu8yfL4mWBF3YhwyBMoFj
    vaultProtoConfig: CjxcyivgP69qEvXvKFbsYjTxavPWwh5UEWwtzbjodwer
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: vDsAiSkWU7E639ofBadRBezw4TYR6u72R3MbGV8j4jd
    vaultTokenBAccount: 29UNqkNsJjc1zgFGr9LYTDE8hSchcUiV7xqj5CPcte74
    vaultTreasuryTokenBAccount: E7oYHeM7v14tv7AjvsxD9tcXQMtLYvZRarTjQ1uqhjSW
    tokenAMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenASymbol: ETH
    tokenBMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenBSymbol: USDC
    swapTokenMint: 34eQAuJnEQ87BXfH4Cj5FS8Defg3TULMyE9WMrTD6st8
    swapTokenAAccount: 9wQtYjthwzGf9zUKP86dySc7sphFkY7H6RBRLCNYuFDS
    swapTokenBAccount: G4D6AexukfkKq1k8YJVaEytM61t39b1XEXjf7gzMkGc4
    swapFeeAccount: 7yAXNH1cxjQod8nCq4tUDKdtTGdePFxCZ88b9Jb8L5Ma
    swapAuthority: 8txrTthVZt7eWJde9zYiieNPZxrgzUds9pPH2oL8Ldvo
    swap: HiKQndMhLQSKiRudNcXVuVB8Y6Raz63z1dA8yeTUCUck
  - vault: CwVN7Ckq2GJ1UmyU62ByzwUycfh2uY8AMBehhdZBYvUM
    vaultProtoConfig: CjxcyivgP69qEvXvKFbsYjTxavPWwh5UEWwtzbjodwer
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: 3gCyMbWwagmQXkWD1dM5mwt9dnnqVKdRv6S8TPmTrbmA
    vaultTokenBAccount: hLiAFV11EPsTXx9jfzvDWFyExNvZCYGohiV2HtLU8BA
    vaultTreasuryTokenBAccount: F3TS7WPPD5hx66zRM6nbaPrDsJxZUEc529wMpdtrrjum
    tokenAMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenASymbol: USDC
    tokenBMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenBSymbol: SOL
    swapTokenMint: 8y9MiAJMwpxLWnKjYmd7oXSJrPKXmyBbQ4jxkz6PsYtQ
    swapTokenAAccount: 5NG9u8R95x8uCvv2C6wn5pZKFJe3tdGDAGGpjtA6EitX
    swapTokenBAccount: 6iFXCNX9e3UVN98qXit6NzoQcyGCPJPpBtMMaDJEzSW5
    swapFeeAccount: 9mf36oT2to64kdz8LdA1DG6iGzAfaRGcYntapckmHhFZ
    swapAuthority: 2zseXJQcHWNgdc7iKkgVo1rtCYFnpNCfWkirvGxwPSBE
    swap: 8vw2VPuJTJmHeWtUDrr4ofRnc6GAg8jxnKcygdtYSTvu
  - vault: CrdeFbLveC3hQCtBBVeiSeMhRUQwopBF8i1QVL3wHWUg
    vaultProtoConfig: CjxcyivgP69qEvXvKFbsYjTxavPWwh5UEWwtzbjodwer
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: Exsek3Ezh1pdhNxcYEU1JDEWJFHRVYkeDKATenphbRbA
    vaultTokenBAccount: BoBML8jQDZz4NCo9WGhDn2bN6eFE7j7238xwjQ3Pmzq1
    vaultTreasuryTokenBAccount: F3TS7WPPD5hx66zRM6nbaPrDsJxZUEc529wMpdtrrjum
    tokenAMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenASymbol: ETH
    tokenBMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenBSymbol: SOL
    swapTokenMint: 8UbN7AxLTzgBzKmUt9hDmyqjKZEzSobYfQwTreiuet6Q
    swapTokenAAccount: Ccuuud5ZCSFLFgP5NH3mxveQZQ32a5oZWGYgP2cWc1xk
    swapTokenBAccount: Eq3aTwUBWCmBsYydNTcJk2EZftYQgEmSzeZ7FJWG7hWH
    swapFeeAccount: 3BxnJFUBkuxMSco6RNPQE3v1d41xfteMfM1eieyqAubz
    swapAuthority: GQdWjXPkzbfMNb2AamvRTZC5ZAzeDdzTfnkc6P1WGedK
    swap: G5aR9mwE6BzUyJmqM5BJPLZowrpLFGCs4pDNMWtdCPM4
  - vault: 9ryxSGaF8pgby9bdFsv2mp4r332JxE3YTbg9FnNKJ8yk
    vaultProtoConfig: CjxcyivgP69qEvXvKFbsYjTxavPWwh5UEWwtzbjodwer
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: 2dqKSRSginr53aQyzbEM7Q75iCQRtXjJrPGqDqd4jiAj
    vaultTokenBAccount: 61JxYYReLavQUj2aSQY4iiNTCecwy8rr6azSdiWodcw1
    vaultTreasuryTokenBAccount: GNwm4sezRcUPvScZm9cbWFRaiwgY8rbkz22cmKzMFaTg
    tokenAMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenASymbol: USDC
    tokenBMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenBSymbol: ETH
    swapTokenMint: 5chmnVTY3No828k2gTu9tYSMZipGqQwBdiAfvyNs4CGh
    swapTokenAAccount: DL9sVeHsVgi9owEDXXJ1PmQABjgwNgeRm3A3nNiPE3j3
    swapTokenBAccount: DL9bq5qJt1dcqX3sQgaKfniPeFf9rMrQ5tBhbb8sVaE2
    swapFeeAccount: XLg1yjkbVjqUW3tyzg6G4eFWrEZv7bUPhdBvEMBbGuL
    swapAuthority: F1Lu83Gz2DrbcZUfuxpbbsXChJiBG4A1MAB1ZNELwXUS
    swap: 6dp7h7pAXGM8G4BTfXYcp9ukXxHTpBDhbswotSSmxnG6
  - vault: 4LAbv2D4mT4YrxBnqaUFcth2vgg2bqdG4P2FRcRZ88Mb
    vaultProtoConfig: CjxcyivgP69qEvXvKFbsYjTxavPWwh5UEWwtzbjodwer
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: GBVCpBfXraecAE6W5soMg87SyvwDZJAiCoJk1KjHB9uU
    vaultTokenBAccount: BhZCbNvdGGZWEKZoRCrWHoxr4c2wbugEyfNJUm9vNzzw
    vaultTreasuryTokenBAccount: GNwm4sezRcUPvScZm9cbWFRaiwgY8rbkz22cmKzMFaTg
    tokenAMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenASymbol: SOL
    tokenBMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenBSymbol: ETH
    swapTokenMint: 6pMxgYuFwqfZKXJwf913tPtwNiV7oQ31ds7nYSHRZuZ3
    swapTokenAAccount: GaBQHSZ3mTCVNpXUiYA1L2oGubNz5igrdCSL3Q1tUzpZ
    swapTokenBAccount: GtwN9Qh2q6PxiCzjQmz8seqHapeHKqh1QnTTiwBphnSi
    swapFeeAccount: 6siHDmACo35bsz9KeZ2v4oCSiAXcgmaSRMYPwWa9PSZ3
    swapAuthority: GwiRNjxJN69A9vGeUDZR93arbZxmbNHF3NwRJvyrcenm
    swap: 4ZR71DbLndtqcve8k39CudABYNx6bfY7v37swkZEF1rM
  - vault: 5G5WZCA4PKW7g4iNmJSiAyrQ7MFznMEFB8wGQYNR7kpf
    vaultProtoConfig: BWdfuPvDnXzaHSPV5i4zG7mToDrYeywZYxptx79hiwmn
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: 62CSXc4jZ6TDTNc6nDdvMUyAyEsWqpoGDDoqEhkxd2or
    vaultTokenBAccount: FubUByA1CusGb52sNcYokGp111F9RexdwNWJhWj8FEXf
    vaultTreasuryTokenBAccount: 9AXU3RYDqVbyuNrj45UH6wXvTEr5YG5YNSEsmHmfKwYf
    tokenAMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenASymbol: SOL
    tokenBMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenBSymbol: USDC
    swapTokenMint: EvzVysRbk6hFg4gb5kqKnJTgcBDD4TYtpxc85yRfBpjj
    swapTokenAAccount: 8QLaWemXhPo68Ytgj88yNbjFfXkv34GBLXE7m65G8Gfu
    swapTokenBAccount: 2LNDYnxa9MwaqkfGbegfWMBCctPmU1xmJxanYiufpP9j
    swapFeeAccount: 7xt4qqPuiyCNHoZQxSM45Mf4wGDyDHMp9wqV5ViyiARY
    swapAuthority: 8okfz4U7RmWg9ujhPGmdC6mvDYwtohD5KDtkAmoMi4Q9
    swap: 5mrxvYhP5usqcg6Xcw7pkRj9Bdi3mwFYPygv9b3aQidZ
  - vault: ELwzSPX17abjjPupGdcQeHRE1Ztg6wvCdcpcqhv7SK1F
    vaultProtoConfig: BWdfuPvDnXzaHSPV5i4zG7mToDrYeywZYxptx79hiwmn
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: EFkvuM5epowptthzV1cVqjw4BD6u7DYBhD1qSbuQTntu
    vaultTokenBAccount: 6MArTX7qv3ZZYErgRQkaZJdNMYFmkqyntf8aezGxJNpo
    vaultTreasuryTokenBAccount: 9AXU3RYDqVbyuNrj45UH6wXvTEr5YG5YNSEsmHmfKwYf
    tokenAMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenASymbol: ETH
    tokenBMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenBSymbol: USDC
    swapTokenMint: 3Jk4A3KB1wamF98X19QEWk2N4GTof5ntvGpy6rdyjK16
    swapTokenAAccount: 8axfrx75LXXMo7bvCjdCEQLGDAsCu5DHH8cntNHspuE9
    swapTokenBAccount: BJbdpQspR6eJqRmPcPFcBj3cccV4tZKQXv1ffH4iMZ8T
    swapFeeAccount: 6s255TUC9UfjJkfARQ176dVK5P3drFtsajKDASnYjLo6
    swapAuthority: 5zCd1h6Ai5uiQxHxKuaJpmDaNKgKEyGPDxddHxAog5ku
    swap: HGaq8Psncc1gnPPdQAXij1QfJqroSnkrJUPNha896yBU
  - vault: AqFvqtTnScAWMzz4gQLvuntnrWVbrvJretjKugFD9RyB
    vaultProtoConfig: BWdfuPvDnXzaHSPV5i4zG7mToDrYeywZYxptx79hiwmn
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: 5oFLcxMHRC47Pp2ZFXxMGkk4GDV4c1VTrGZJtiArMm12
    vaultTokenBAccount: 4VDWEsAuwdRtspYpQVVsbCGetKPzeLwotpmTKcf1Qqa3
    vaultTreasuryTokenBAccount: 89MkxjXRguUmNB9iGtGHcHfCqctNVp1WtvowtwfzfrGb
    tokenAMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenASymbol: USDC
    tokenBMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenBSymbol: SOL
    swapTokenMint: CnHx9VzekDr1gyW1BwTVV3cLh78bbQpk8MsWXTNda4dy
    swapTokenAAccount: G5kpKtzkfCjdAPcXxsRcTSZUkq7JfY2JJLXMVMtnUqxZ
    swapTokenBAccount: ECtQnhy877Ug2g1S9uwrkAqwMGwTqiM68xdfPEMj9fWB
    swapFeeAccount: 3vyFyqThZ6mEaQb4hK5Z8zn55M6VYyfHZNf9p9Mx652s
    swapAuthority: DTmhtwcRv8iaCSKB6VRioKq3k1HbaFcCzTWe2YVxSUqg
    swap: 4BYTEHvhTQPZRMCpgKMtaPoCiuib5ugKF35pbAvxRrXR
  - vault: BxCkh1yNv7EGqFEEXcWNgengXdVcHDQekxovE2DJVRUE
    vaultProtoConfig: BWdfuPvDnXzaHSPV5i4zG7mToDrYeywZYxptx79hiwmn
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: Eb7TF2GGPBgNY69iPRZ2rf3jrn2cVPmrxdsfb4YJhxAa
    vaultTokenBAccount: 26i26zSJBhaCpsZuFHYLXw1LfPAjHUU5XyaV4GkUmXdJ
    vaultTreasuryTokenBAccount: 89MkxjXRguUmNB9iGtGHcHfCqctNVp1WtvowtwfzfrGb
    tokenAMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenASymbol: ETH
    tokenBMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenBSymbol: SOL
    swapTokenMint: EMrcpj4HekAd1rsLudHa5Lc7CTVE5y4UXb8834HV7H7o
    swapTokenAAccount: BML7Ex9FZjtgKHG916yo198A7LWp9FsmCkni2WiDpxH4
    swapTokenBAccount: BVTi44KFYTMZ3fQb5jLXXBvGZqKnjHWGPT58f8NSBGqR
    swapFeeAccount: BJwHNEGMdtnfpmR8UHtwzLz6MHnMZbcgYmruA5xm8kUq
    swapAuthority: 3ujjc7HmCEVX1HppZuNY1gzNSv4tV3gBXWn1hKwUDEm8
    swap: AArdwjy6JRQmUtJ33aueZHwU9HbjUb5K873ip2Da53zW
  - vault: BQm4SqSWrBNBYfLZaFnbSLvZpkLddj869S8JrL1uSL2F
    vaultProtoConfig: BWdfuPvDnXzaHSPV5i4zG7mToDrYeywZYxptx79hiwmn
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: 44k918RwXofNs6vcnL2j4k7f2oVJV5eBPrj7WqeE5LNd
    vaultTokenBAccount: Hd4t1EVN7fpYuoxY8kxTefXDXrGK9SKpkFV5YJFPzh7h
    vaultTreasuryTokenBAccount: 3W2V9MgRKwE24t8LBU6xnsEVMu2Aqib8TGJjSjBNEDnA
    tokenAMint: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
    tokenASymbol: USDC
    tokenBMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenBSymbol: ETH
    swapTokenMint: HsBCG3vic6aDryxVP3HR9PFpqEcNcc44AUaJP71oKHpn
    swapTokenAAccount: 3nNT13VyUx7rjafMm2ife2b5UPfPqTRgGrqPcD2DtVoC
    swapTokenBAccount: FtzZkBa23Cdm7Qe4MiJknjDxRbLCh39wEuAenkgJima5
    swapFeeAccount: ER9UgH5tmysRSEi8xfdJBEijDmNhLToQrymLFNqQeLt7
    swapAuthority: Gp3TtxmCzM5N1T1WKKpJnx237AAtWcDgWv4ZeH3Z6aRL
    swap: BcNoEX4XJeiXecAKgkKVTMU3TkpLUZSTCzSwk7Kn7Lft
  - vault: 8vHgvjJ6PmuiEL99wm3ojmU7utJ7Rawqys4Z8BgWbiG4
    vaultProtoConfig: BWdfuPvDnXzaHSPV5i4zG7mToDrYeywZYxptx79hiwmn
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: A4ASDaAUfvNzK7LEZQo6caz1scGnRjt13g98RL6EFZ3q
    vaultTokenBAccount: G8yB4aQw7brf3vVFF7NyT4N9tDNCXM771God1jtThcVx
    vaultTreasuryTokenBAccount: 3W2V9MgRKwE24t8LBU6xnsEVMu2Aqib8TGJjSjBNEDnA
    tokenAMint: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
    tokenASymbol: SOL
    tokenBMint: 54uPbRrVwYsvZZMmsCXjLCtshgTquBWDZTNTJNbEDZ4H
    tokenBSymbol: ETH
    swapTokenMint: AW3WoRvtsCtu74BRGiUiULkRswrBbT3cnoU3FHBkPTqL
    swapTokenAAccount: AdWnvjSQJHRfaQfhyjc7LLwYur8WtyrrC8wk34WnpTzS
    swapTokenBAccount: 2jenLVuMqxpTipLz6KUg4MS2gJV3sSCFCRsy5rYW7qMv
    swapFeeAccount: J17vvwGNP5i867oC9WbD7djHjRr3ut3NEyxdj3czxoK9
    swapAuthority: 5s3TTqV6kYWrobVqoXhEYJdupZ33VPJE2jXLgibmWRki
    swap: FN7LaD6GZCxenG3wwYNqW6pf1R4zbrfuePJP8DVYe3CX

